name: SonarQube Scan

on:
  push:
    branches:
      - main  # Trigger the scan on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the scan on PR targeting the main branch

jobs:
  sonarqube_scan:
    runs-on: windows-latest  # Run on the latest Windows runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (required for SonarScanner)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Install dependencies (for example, npm for a Node.js project)
      - name: Install dependencies
        run: |
          npm install  # Adjust this based on your project's dependency manager

      # Step 4: Install SonarScanner CLI
      - name: Install SonarScanner
        run: |
          Invoke-WebRequest -Uri "https://downloads.sonarqube.org/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-windows.zip" -OutFile "sonar-scanner.zip"
          Expand-Archive -Path "sonar-scanner.zip" -DestinationPath "$env:USERPROFILE"
          $env:PATH += ";$env:USERPROFILE\sonar-scanner-4.8.0.2856-windows\bin"
          Write-Host "SonarScanner added to PATH"

      # Step 5: Run SonarQube scanner to analyze the repository
      - name: Run SonarQube scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=<Your-Project-Key> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$env:SONAR_TOKEN  # Use a GitHub secret for your SonarQube token

      # Optional: Cache dependencies to speed up future runs
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
