name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-scanner:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Install dependencies
      run: |
        choco install curl wget -y

    - name: Download SonarScanner
      run: |
        mkdir -p ${{ github.workspace }}/sonar-scanner
        curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-windows-x64.zip
        tar -xvf sonar-scanner-cli.zip -C ${{ github.workspace }}/sonar-scanner

    - name: Set SONAR_SCANNER_HOME
      run: echo "SONAR_SCANNER_HOME=${{ github.workspace }}/sonar-scanner/sonar-scanner-6.2.1.4610-windows-x64" >> $GITHUB_ENV

    - name: Add SonarScanner to PATH
      run: |
        echo "${{ github.workspace }}/sonar-scanner/sonar-scanner-6.2.1.4610-windows-x64/bin" >> $GITHUB_PATH

    - name: Run SonarQube analysis in debug mode
      run: |
        sonar-scanner.bat -X -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
                          -Dsonar.sources=. \
                          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
