name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_scan:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Java JDK 11 using Eclipse Adoptium
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adoptopenjdk'
        java-version: '11'

    - name: Set up SonarQube scanner
      run: |
        mkdir -p 'D:\a\_temp/sonarscanner'
        cd 'D:\a\_temp/sonarscanner'
        SCANNER_FILE_NAME=sonarqube-25.1.0.102122.zip
        SCANNER_URI=https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.1.0.102122.zip
        curl --fail --silent --show-error --user-agent sonarqube-scan-action --location --output $SCANNER_FILE_NAME $SCANNER_URI
        unzip -q -o $SCANNER_FILE_NAME
        SCANNER_UNZIP_FOLDER=sonarqube-25.1.0.102122
        SCANNER_LOCAL_FOLDER='D:\a\_temp/sonarqube-25.1.0.102122'
        mv -f $SCANNER_UNZIP_FOLDER $SCANNER_LOCAL_FOLDER
        echo "${SCANNER_LOCAL_FOLDER}/bin" >> $GITHUB_PATH

    - name: Run SonarQube scanner with secret URL and code
      run: |
        echo "Running SonarQube Scan"
        sonar-scanner.bat -Dsonar.projectBaseDir=. -Dsonar.projectKey=${{ secrets.sqp_c930cdf8516d54db6df4a5b81419fb402ea14665 }} -Dsonar.sources=. -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.host.url=${{ secrets.https://cherry-xbox-mechanism-ctrl.trycloudflare.com  }}
        
    - name: Display success message
      run: echo "SonarQube scan completed successfully!"
