name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for better SonarQube analysis

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin JDK 17
          java-version: '17'

      - name: Cache SonarQube Scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-scanner-cli-6.2.1.4610-Linux-X64
          restore-keys: |
            sonar-scanner-cli-

      # If your project uses Maven, uncomment this
      - name: Build Project with Maven
        run: mvn clean install -DskipTests  # Adjust if tests should run

      # If your project uses Gradle, uncomment this instead
      # - name: Build Project with Gradle
      #   run: ./gradlew build -x test  # Adjust if tests should run

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=whitehackzzz_SonarQube-test999_2d38b142-ff2a-442f-bcfd-a57508bbd163 \
            -Dsonar.sources=src \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} -X  # Debug enabled
