name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check if SonarScanner is already installed
        run: |
          if (-Not (Test-Path "C:\sonar-scanner\sonar-scanner-5.0.1.3006-windows\bin\sonar-scanner.bat")) {
            Write-Host "SonarScanner not found, downloading..."
            Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" -OutFile "sonar-scanner.zip"
            Expand-Archive -Path sonar-scanner.zip -DestinationPath "C:\sonar-scanner" -Force
            echo "C:\sonar-scanner\sonar-scanner-5.0.1.3006-windows\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
          } else {
            Write-Host "SonarScanner already installed."
          }

      - name: Run SonarQube Scan
        run: |
          sonar-scanner.bat ^
            "-Dsonar.projectKey=whitehackzzz_SonarQube-test999_2d38b142-ff2a-442f-bcfd-a57508bbd163" ^
            "-Dsonar.sources=." ^
            "-Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}" ^
            "-Dsonar.login=${{ secrets.SONAR_TOKEN }}"
