name: CI/CD Workflow for SonarQube Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (if your project requires Java for analysis)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Step 3: Run the SonarQube Scanner
      - name: SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.projectKey=whitehackzzz_SonarQube-test999_43896c4c-8e09-4909-965d-897465f7d07d \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
